#!/bin/sh
#
# Get radio list for (PRODUCT, OPERATOR, USER) 
#

RADIO_SERVER=$(kdb get system/config/radio/server)
RADIO_DIRECTORY=$(kdb get system/config/radio/directory)
PRODUCT=$(kdb get system/config/radio/product)
OPERATOR=$(kdb get system/config/radio/operator)
USERNAME=$(kdb get system/config/radio/username)
PASSWORD=$(kdb get system/config/radio/password)
ETH_MAC=$(kdb get system/redboot/eth_mac)
NOUPDATE_RADIO=$(kdb get system/config/radio/noupdate)
RADIO_LANGUAGE=$(kdb get system/config/radio/language)
RADIOLIST_IN="/tmp/radioList.xml"
RADIOLIST_OUT="/etc/upnp/media_server/radioList.xml"
UPDATING=1
NOUPDATING=0

# Thomson radio server 
if [ "$NOUPDATE_RADIO" != "1" ]; then
	wget -T 15 -t 2 "http://$USERNAME:$PASSWORD@$RADIO_SERVER/$RADIO_DIRECTORY/get_radio_list.php?product=$PRODUCT&operator=$OPERATOR&user=$ETH_MAC&language=$RADIO_LANGUAGE" -O "$RADIOLIST_IN"
    	if [ -s "$RADIOLIST_IN" ]; then
		# check radio list
		RADIO_CHECK=$(grep "<radiolist>" "$RADIOLIST_IN")
		RADIO_CHECK_END=$(grep "</radiolist>" "$RADIOLIST_IN")
		if [ -n "$RADIO_CHECK" ] && [ -n "$RADIO_CHECK_END" ]; then
			#check MD5		  
		     	s1=$(md5sum "$RADIOLIST_IN" | cut -d " " -f 1)
			s2=0
                       	[ -f $RADIOLIST_OUT ] && s2=$(md5sum "$RADIOLIST_OUT"  | cut -d " " -f 1)
			if [ $s1 != $s2 ]; then 
				#check version
				VERSION=$(grep '<version>' "$RADIOLIST_IN" | sed 's/<version>\([0-9].[0-9]*\).*/\1/')
				OLD_VERSION=$(grep '<version>' "$RADIOLIST_OUT" | sed 's/<version>\([0-9].[0-9]*\).*/\1/')
                       		if [ -z "$VERSION" ] || [ -z "$OLD_VERSION" ] || [ $VERSION != $OLD_VERSION ]; then 
	   				mv "$RADIOLIST_IN" "$RADIOLIST_OUT"
					if [ -z "$VERSION" ];then
						VERSION="0"
					fi
					echo "get_radio list new list " "$VERSION" 
					kdb set system/runtime/upnp_media_server/radio_list_version "$VERSION"
				else
					echo "get_radio same version " "$OLD_VERSION" 
				fi
			else
				echo "get_radio  same MD5 "
			fi
		else
			echo "get_radio error on balise  ""$RADIO_CHECK"  "$RADIO_CHECK_END" 
		fi
	else
		echo "get_radio error fail to get radio list  "
	fi
else
		echo "get_radio NOUPDATE_RADIO  "
fi
