#!/bin/sh
#
# Start the upnp control point
#
. /etc/config

case $1 in
    start)
        /bin/echo "Starting UPnP Control Point ..."
        spawn respawn "/usr/bin/upnp_control_point"
        ;;
    stop)
        /bin/echo "Stopping UPnP Control Point ..."
        spawn cancel "/usr/bin/upnp_control_point"
        ;;
    restart)
	$0 stop
	$0 start
	;;
    *)
esac

