#!/bin/sh

KDB=/bin/kdb
KDB_PODCAST_STATUS=system/config/radio/myradio/check

header() {
echo "Content-type: text/plain"
echo
}

kdbget() {
    echo ""
    for i in 0 1 2 3 4 5 6 7 8 9; do
        echo "$($KDB get $1$i) ;"
    done
}

header
kdbget $KDB_PODCAST_STATUS
